export const roles = {
  SUPER_ADMIN: "superAdmin",
  ADMIN: "admin",
  HR: "hr",
  MANAGER: "manager",
  EMPLOYEE: "employee",
  CLIENT: "client",
};

export const scope = {
  ANY: "any",
  ORGANIZATION: "org",
  TEAM: "team",
  OWN: "own",
};

export const apiTags = {
  USERS: "Users",
  CLIENTS: "Clients",
  ORGANIZATIONS: "Organizations",
  ATTENDANCE: "Attendance",
  LEAVES: "Leaves",
  REQUESTS: "Requests",
  ANALYTICS: "Analytics",
};

export const allowedModulesByRole = {
  [roles.SUPER_ADMIN]: [
    "dashboard",
    "users",
    "settings",
    "attendance",
    "leaves",
    "requests",
    "profile",
  ],
  [roles.ADMIN]: [
    "dashboard",
    "users",
    "attendance",
    "leaves",
    "requests",
    "profile",
  ],
  [roles.HR]: [
    "dashboard",
    "users",
    "attendance",
    "leaves",
    "requests",
    "profile",
  ],
  [roles.MANAGER]: ["dashboard", "users", "requests", "profile"],
  [roles.EMPLOYEE]: ["dashboard", "attendance", "leaves", "profile"],
  [roles.CLIENT]: ["dashboard", "profile"],
};

export const DEPARTMENTS = [
  { value: "humanResources", label: "Human Resources (HR)" },
  { value: "financeAccounting", label: "Finance & Accounting" },
  { value: "informationTechnology", label: "Information Technology (IT)" },
  { value: "sales", label: "Sales" },
  { value: "marketing", label: "Marketing" },
  { value: "customerSupport", label: "Customer Support / Service" },
  { value: "operations", label: "Operations" },
  { value: "administration", label: "Administration" },
  { value: "legalCompliance", label: "Legal / Compliance" },
  { value: "procurementPurchasing", label: "Procurement / Purchasing" },
  { value: "researchDevelopment", label: "Research & Development (R&D)" },
  { value: "productManagement", label: "Product Management" },
  { value: "businessDevelopment", label: "Business Development" },
  { value: "logisticsSupplyChain", label: "Logistics & Supply Chain" },
];

export const leavesType = {
  SICK: "sick",
  CASUAL: "casual",
  ANNUAL: "annual",
  UNPAID: "unpaid",
  MATERNITY: "maternity",
  PATERNITY: "paternity",
};

export const leaveStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

export const countries = {
  AFGHANISTAN: "afghanistan",
  ALBANIA: "albania",
  ALGERIA: "algeria",
  ANDORRA: "andorra",
  ANGOLA: "angola",
  ARGENTINA: "argentina",
  ARMENIA: "armenia",
  AUSTRALIA: "australia",
  AUSTRIA: "austria",
  AZERBAIJAN: "azerbaijan",
  BAHAMAS: "bahamas",
  BAHRAIN: "bahrain",
  BANGLADESH: "bangladesh",
  BARBADOS: "barbados",
  BELARUS: "belarus",
  BELGIUM: "belgium",
  BELIZE: "belize",
  BENIN: "benin",
  BHUTAN: "bhutan",
  BOLIVIA: "bolivia",
  BOSNIA_AND_HERZEGOVINA: "bosnia and herzegovina",
  BOTSWANA: "botswana",
  BRAZIL: "brazil",
  BRUNEI: "brunei",
  BULGARIA: "bulgaria",
  BURKINA_FASO: "burkina faso",
  BURUNDI: "burundi",
  CAMBODIA: "cambodia",
  CAMEROON: "cameroon",
  CANADA: "canada",
  CAPE_VERDE: "cape verde",
  CENTRAL_AFRICAN_REPUBLIC: "central african republic",
  CHAD: "chad",
  CHILE: "chile",
  CHINA: "china",
  COLOMBIA: "colombia",
  COMOROS: "comoros",
  CONGO: "congo",
  COSTA_RICA: "costa rica",
  CROATIA: "croatia",
  CUBA: "cuba",
  CYPRUS: "cyprus",
  CZECH_REPUBLIC: "czech republic",
  DENMARK: "denmark",
  DJIBOUTI: "djibouti",
  DOMINICA: "dominica",
  DOMINICAN_REPUBLIC: "dominican republic",
  ECUADOR: "ecuador",
  EGYPT: "egypt",
  EL_SALVADOR: "el salvador",
  EQUATORIAL_GUINEA: "equatorial guinea",
  ERITREA: "eritrea",
  ESTONIA: "estonia",
  ESWATINI: "eswatini",
  ETHIOPIA: "ethiopia",
  FIJI: "fiji",
  FINLAND: "finland",
  FRANCE: "france",
  GABON: "gabon",
  GAMBIA: "gambia",
  GEORGIA: "georgia",
  GERMANY: "germany",
  GHANA: "ghana",
  GREECE: "greece",
  GRENADA: "grenada",
  GUATEMALA: "guatemala",
  GUINEA: "guinea",
  GUINEA_BISSAU: "guinea-bissau",
  GUYANA: "guyana",
  HAITI: "haiti",
  HONDURAS: "honduras",
  HUNGARY: "hungary",
  ICELAND: "iceland",
  INDIA: "india",
  INDONESIA: "indonesia",
  IRAN: "iran",
  IRAQ: "iraq",
  IRELAND: "ireland",
  ISRAEL: "israel",
  ITALY: "italy",
  IVORY_COAST: "ivory coast",
  JAMAICA: "jamaica",
  JAPAN: "japan",
  JORDAN: "jordan",
  KAZAKHSTAN: "kazakhstan",
  KENYA: "kenya",
  KIRIBATI: "kiribati",
  KOSOVO: "kosovo",
  KUWAIT: "kuwait",
  KYRGYZSTAN: "kyrgyzstan",
  LAOS: "laos",
  LATVIA: "latvia",
  LEBANON: "lebanon",
  LESOTHO: "lesotho",
  LIBERIA: "liberia",
  LIBYA: "libya",
  LIECHTENSTEIN: "liechtenstein",
  LITHUANIA: "lithuania",
  LUXEMBOURG: "luxembourg",
  MADAGASCAR: "madagascar",
  MALAWI: "malawi",
  MALAYSIA: "malaysia",
  MALDIVES: "maldives",
  MALI: "mali",
  MALTA: "malta",
  MARSHALL_ISLANDS: "marshall islands",
  MAURITANIA: "mauritania",
  MAURITIUS: "mauritius",
  MEXICO: "mexico",
  MICRONESIA: "micronesia",
  MOLDOVA: "moldova",
  MONACO: "monaco",
  MONGOLIA: "mongolia",
  MONTENEGRO: "montenegro",
  MOROCCO: "morocco",
  MOZAMBIQUE: "mozambique",
  MYANMAR: "myanmar",
  NAMIBIA: "namibia",
  NAURU: "nauru",
  NEPAL: "nepal",
  NETHERLANDS: "netherlands",
  NEW_ZEALAND: "new zealand",
  NICARAGUA: "nicaragua",
  NIGER: "niger",
  NIGERIA: "nigeria",
  NORTH_KOREA: "north korea",
  NORTH_MACEDONIA: "north macedonia",
  NORWAY: "norway",
  OMAN: "oman",
  PAKISTAN: "pakistan",
  PALAU: "palau",
  PALESTINE: "palestine",
  PANAMA: "panama",
  PAPUA_NEW_GUINEA: "papua new guinea",
  PARAGUAY: "paraguay",
  PERU: "peru",
  PHILIPPINES: "philippines",
  POLAND: "poland",
  PORTUGAL: "portugal",
  QATAR: "qatar",
  ROMANIA: "romania",
  RUSSIA: "russia",
  RWANDA: "rwanda",
  SAINT_KITTS_AND_NEVIS: "saint kitts and nevis",
  SAINT_LUCIA: "saint lucia",
  SAINT_VINCENT_AND_THE_GRENADINES: "saint vincent and the grenadines",
  SAMOA: "samoa",
  SAN_MARINO: "san marino",
  SAO_TOME_AND_PRINCIPE: "sao tome and principe",
  SAUDI_ARABIA: "saudi arabia",
  SENEGAL: "senegal",
  SERBIA: "serbia",
  SEYCHELLES: "seychelles",
  SIERRA_LEONE: "sierra leone",
  SINGAPORE: "singapore",
  SLOVAKIA: "slovakia",
  SLOVENIA: "slovenia",
  SOLOMON_ISLANDS: "solomon islands",
  SOMALIA: "somalia",
  SOUTH_AFRICA: "south africa",
  SOUTH_KOREA: "south korea",
  SOUTH_SUDAN: "south sudan",
  SPAIN: "spain",
  SRI_LANKA: "sri lanka",
  SUDAN: "sudan",
  SURINAME: "suriname",
  SWEDEN: "sweden",
  SWITZERLAND: "switzerland",
  SYRIA: "syria",
  TAIWAN: "taiwan",
  TAJIKISTAN: "tajikistan",
  TANZANIA: "tanzania",
  THAILAND: "thailand",
  TIMOR_LESTE: "timor-leste",
  TOGO: "togo",
  TONGA: "tonga",
  TRINIDAD_AND_TOBAGO: "trinidad and tobago",
  TUNISIA: "tunisia",
  TURKEY: "turkey",
  TURKMENISTAN: "turkmenistan",
  TUVALU: "tuvalu",
  UGANDA: "uganda",
  UKRAINE: "ukraine",
  UNITED_ARAB_EMIRATES: "united arab emirates",
  UNITED_KINGDOM: "united kingdom",
  UNITED_STATES: "united states",
  URUGUAY: "uruguay",
  UZBEKISTAN: "uzbekistan",
  VANUATU: "vanuatu",
  VATICAN_CITY: "vatican city",
  VENEZUELA: "venezuela",
  VIETNAM: "vietnam",
  YEMEN: "yemen",
  ZAMBIA: "zambia",
  ZIMBABWE: "zimbabwe",
};

export const requestTypes = [
  { value: "document", label: "Document" },
  { value: "wfh", label: "Work From Home" },
  { value: "resetPassword", label: "Reset Password" },
];

export const MARITAL_STATUSES = [
  { value: "single", label: "Single" },
  { value: "married", label: "Married" },
  { value: "divorced", label: "Divorced" },
  { value: "widowed", label: "Widowed" },
];

export const BLOOD_GROUPS = [
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
];
